services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: docker-compose
    ports:
      - 8080:8080

  doc:
    image: swaggerapi/swagger-ui:v5.17.14
    depends_on:
      - app
    ports:
      - 80:8080
    environment:
      SWAGGER_JSON_URL: http://localhost:8080/openapi.yam
