on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - run: make build VERSION=${{ github.ref_name }}
      - run: make test
      - run: make docker VERSION=${{ github.ref_name }} TAG=${{ github.ref_name }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
